
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SchoolDeal
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  config-location: classpath:mybatis/mybatis.xml
  mapper-locations: classpath:mybatis/mapper/*.xml